root = "./testdata"

[[sources]]
file = "https://raw.githubusercontent.com/eankeen/eankeen/main/readme.md"
destFile = "one"

[[sources]]
prefix = "https://raw.githubusercontent.com/eankeen/deno-babel/dev/"
files = [".gitattributes", ".gitignore", ".gitmodules"]
postfix = ""
destPrefix = "more"
destPostfix = ""
